name: CI

on:
  push:
    branches:
      - "main"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2.1.1
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple

      # Standard build tasks
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Test
        run:  make test
      - name: Build
        run:  make cross-platform
      - name: Lint
        run: make check
      - name: Permissions
        run: chmod a+x faas_*amd*

      # Upload all build artifacts whether it's a release or not
      - uses: actions/upload-artifact@v2
        with:
          name: OSX Binary
          path: faas_darwin_amd64
      - uses: actions/upload-artifact@v2
        with:
          name: Linux Binary
          path: faas_linux_amd64
      - uses: actions/upload-artifact@v2
        with:
          name: Windows Binary
          path: faas_windows_amd64.exe

      # Build and push a latest image with each commit
      - name: Image
        run:  make image
      - name: Push Image
        env:
          USER: ${{ secrets.QUAY_USER }}
          PASS: ${{ secrets.QUAY_TOKEN }}
        run: |
          docker login -u "$USER" -p "$PASS" quay.io
          make push && make latest

      # The following steps are only executed if this is a release
      - name: Compress Binaries
        if: ${{ steps.release.outputs.release_created }}
        run: gzip faas_darwin_amd64 faas_linux_amd64 faas_windows_amd64.exe
      - name: Upload Darwin Binary
        uses: actions/upload-release-asset@v1
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./faas_darwin_amd64.gz
          asset_name: faas_darwin_amd64.gz
          asset_content_type: application/x-gzip
      - name: Upload Linux Binary
        uses: actions/upload-release-asset@v1
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./faas_linux_amd64.gz
          asset_name: faas_linux_amd64.gz
          asset_content_type: application/x-gzip
      - name: Upload Windows Binary
        uses: actions/upload-release-asset@v1
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./faas_windows_amd64.exe.gz
          asset_name: faas_windows_amd64.exe.gz
          asset_content_type: application/x-gzip
      - name: Create Release
        id: create_release
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
