# Build and test every push to the develop branch.
#
# NOTE: Seprate workflows per Branch
# The README contains a build status badge for each of the two primary branches
# main and develop.  However, since the badge does not support unique labels
# (though it does support `?branch`) it appears to the reader as a duplicate
# status badge.  We therefore separate the workflows entirely such that they
# have unique names:  'Main', 'Develop'
name: Develop

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Test
        run:  make test
      - name: Build
        run:  make cross-platform
      - name: Lint
        run: make check
      - name: Permissions
        run: chmod a+x faas_*amd*
      - uses: actions/upload-artifact@v2
        with:
          name: OSX Binary
          path: faas_darwin_amd64
      - uses: actions/upload-artifact@v2
        with:
          name: Linux Binary
          path: faas_linux_amd64
      - uses: actions/upload-artifact@v2
        with:
          name: Windows Binary
          path: faas_windows_amd64.exe