# Build and test all pull requests
name: Pull Requests

on: [pull_request]

jobs:
  integration-test:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
      - name: Fetch Binaries
        run: ./hack/binaries.sh
      - name: Allocate Cluster
        run: ./hack/allocate.sh
      - name: Configure Cluster
        run: ./hack/configure.sh
      - name: Integration Test
        run: go test -tags integration -v -run=TestNew
